name: 'hydrab_fleet'
version: '1.0.0'
config-version: 2

profile: 'hydrab_fleet'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  hydrab_fleet:
    staging:
      +schema: SILVER
      +materialized: table
    marts:
      +schema: GOLD
      +materialized: table
