hydrab_fleet:
  target: prod
  outputs:
    prod:
      type: snowflake
      account: '{{ env_var("SNOWFLAKE_ACCOUNT") }}'
      user: '{{ env_var("SNOWFLAKE_USER") }}'
      role: ACCOUNTADMIN
      database: '{{ env_var("SNOWFLAKE_DATABASE") }}'
      schema: GOLD
      warehouse: HYDRAB_HOL_WH
      threads: 4
